In [22]:
import pandas as pd
import numpy as np

In [11]:
#데이터 파일 로드
#names로 컬럼명 지정
df = pd.read_csv('./naver_shopping.txt', delimiter='\t', names=['rating', 'review'])
df.head()

   rating                                             review
0       5                                            배공빠르고 굿
1       2                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2       5  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3       2  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4       5                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ

In [12]:
#결측치 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   rating  200000 non-null  int64
 1   review  200000 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.1+ MB

In [14]:
#rating 분포 확인
df.rating.value_counts().sort_index(ascending=False)

rating
5    81177
4    18786
2    63989
1    36048
Name: count, dtype: int64

#### 결측치 확인 -> 결측치 없음
#### rating 분포 확인 -> 5,4점 // 1,2, 점으로 별점(레이팅)에 따라 긍정 / 부정으로 나누기로 결정
#### 학습을 위해 target 컬럼을 만들고 5,4 레이팅은 1(긍정) 으로 // 1,2, 레이팅은 0(부정)으로 2진 분류 결정

In [ ]:
#새로운 컬럼에 라벨링
#rating값이 4또는5라면 1로 아니면 0
df['tartget'] = ((df['rating']==4) | (df['rating']==5)).astype(int)

In [20]:
df

        rating                                             review  tartget
0            5                                            배공빠르고 굿        1
1            2                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고        0
2            5  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...        1
3            2  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...        0
4            5                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ        1
...        ...                                                ...      ...
199995       2                                    장마라그런가!!! 달지않아요        0
199996       5  다이슨 케이스 구매했어요 다이슨 슈퍼소닉 드라이기 케이스 구매했어요가격 괜찮고 배송...        1
199997       5                    로드샾에서 사는것보다 세배 저렴하네요 ㅜㅜ 자주이용할께요        1
199998       5                                      넘이쁘고 쎄련되보이네요~        1
199999       5   아직 사용해보지도않았고 다른 제품을 써본적이없어서 잘 모르겠지만 ㅎㅎ 배송은 빨랐습니다        1

[200000 rows x 3 columns]

In [21]:
#데이터 균형 확인
df.tartget.value_counts()

tartget
0    100037
1     99963
Name: count, dtype: int64

### 부정이 10만건, 긍정이 9만9천건으로 타겟 불균형 없다고 판단 가능

In [ ]:
#리뷰의 길이 확인


df_length = [review for review in df['review'] review.strip()]

# df_length = df['review'].astype(str).apply(len)
# df_length.head()

0      7
1     29
2     68
3    136
4     33
Name: review, dtype: int64